config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "instruments#index"

  # resources :users do
  #   collection do
  #     # get 'path', to: 'CONTROLLER#ACTION'
  get 'profile/all_requests', to: 'dashboard#all_requests'
  get 'profile/my_requests', to: 'dashboard#my_requests'
  get 'profile', to: 'dashboard#profile'
      # get 'dashboard#all_requests'
      # get 'dashboard#my_requests'
      # get 'dashboard#profile'
  #   end
  # end

  resources :users, only: [:new, :create]

  resources :instruments do
    resources :users, only: [:show]
    resources :requests, only: [:new, :create]
  end

  resources :requests, only: [:show] do
    resources :reviews, only: [:new, :create]
   end
  
  resources :requests, only: [:show] do
    member do
      post 'accept'
      post 'decline'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  belongs_to :user
  has_one_attached :photo

  has_many :request, dependent: :destroy
  has_many :reviews, :through => :request

  include PgSearch::Model
  pg_search_scope :basic_search,
  against: [ :name, :description ],
  using: {
    tsearch: { prefix: true }
  }

end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :instrument
  has_one :review, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :request
  validates :instrument_stars, inclusion: { in: [1, 2, 3, 4, 5] }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :requests
  has_many :reviews, :through => :requests

  has_many :outgoing_requests, foreign_key: "user_id", class_name: "Request"

  has_many :instruments
  has_many :requests, through: :instruments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
# before_action :find_user

  # def all_requests
  #   # requests = incoming
  #   #Instruments belong to current user
  #   @user = current_user
  #   @requests = []
  #   all_my_instruments = Instrument.where(user: @user)
  #   all_my_instruments.each do |instrument|
  #   @requests << instrument.request if instrument.request != nil
  #   end
  #   @requests.flatten!
  # end


  def profile
    @user = current_user
    @my_requests = current_user.outgoing_requests
    @requests = current_user.requests
  end

  def request_accepted?
    @requests.accepted
  end

  # POST /requests/:id/accept
  def accept
    @request = Request.find(params[:id])
    @request.accepted = 'accepted'
    @request.save
    redirect_to profile_path
  end

  def decline
    @request = Request.find(params[:id])
    @request.status = 'declined'
    @request.save
    redirect_to profile_path
  end

end

app/controllers/instruments_controller.rb
 class InstrumentsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :new]
  def index
    if params[:instrument].present?
        @instruments = Instrument.basic_search(params[:instrument][:name])
    else
     @instruments = Instrument.all
    end
  end

  def show
    @instrument = Instrument.find(params[:id])
  end

  def new
    @instrument = Instrument.new
  end

  def create
    @instrument = Instrument.new(instrument_params)
    @instrument.user = current_user
    if @instrument.save
      redirect_to instruments_path(@instrument)
    else
      render :new
    end
  end

  def edit
    @instrument = Instrument.find(params[:id])
    require_owner!(@instrument)
  end

  def update
    @instrument = Instrument.find(params[:id])
    require_owner!(@instrument)

    @instrument.update(instrument_params)
    redirect_to instrument_path(@instrument)
  end

  def destroy
    @instrument = Instrument.find(params[:id])
    require_owner!(@instrument)

    @instrument.destroy
    redirect_to instruments_path
  end

  private

  def instrument_params
    params.require(:instrument).permit(:name, :price, :description, :photo, :user_id)
  end

  def require_owner!(instrument)
    if (current_user != instrument.user)
      flash[:notice] = 'You are not authorized to do this.'
      redirect_to instruments_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def show
    @request = Request.find(params[:id])
    @instrument = @request.instrument
    @review = Review.new
  end

  def new
    @instrument = Instrument.find(params[:instrument_id])
    @request = Request.new
  end

  def create
    @instrument = Instrument.find(params[:instrument_id])
    @request = Request.new(request_params)

    @request.user_id = current_user.id
    @request.instrument_id = @instrument.id

    if @request.save
      redirect_to request_path(@request)
    else
      render :new
    end
  end

    def accept
    @request = Request.find(params[:id])
    @request.status = 'accepted'
    @request.save
    redirect_to profile_path
  end


  def decline
    @request = Request.find(params[:id])
    @request.status = 'declined'
    @request.save
    redirect_to profile_path
  end

  private

  def request_params
    params.require(:request).permit(:user_id, :instrument_id, :start_date, :end_date)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @request = Request.find(params[:request_id])
  end

  def create
    @review = Review.new(review_params)
    @request = Request.find(params[:request_id])
    if current_user.id == @request.user_id
      @review.request = @request
      if @review.save
        redirect_to instrument_path(@review.request.instrument)
      else
        render :new
      end
    else
      # flash[:notice] = 'You are not authorized to do this.'
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def review_params
    params.require(:review).permit(:instrument_stars, :instrument_review)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/_incoming_requests.html.erb
<div class="container">
  <div class="col mb-5">
    <div class="mb-50">
      <% requests.each do |request| %>
      <div class="card-product">
        <% if request.instrument.photo.attached? %>
        <%= cl_image_tag request.instrument.photo.key, class: 'card-product image', crop: :fill%>
        <% else %>
        <%= image_tag 'instrument-placeholder.jpg', class: 'card-product image' %>
        <% end %>
        <!-- <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" /> -->
        <div class="card-product-infos">
          <h2><%= request.instrument.name %></h2>
          <p>Date: <strong><%= request.start_date %> till <%= request.end_date %></strong></p>
          <p><%= request.user.first_name%> want's to rent your instrument</p>
          <div class="card-checkbox">
            <ul>
              <li>
                <%= link_to accept_request_path(request), method: :post do  %>
                <i id="accept" class="fa fa-check">Accept</i>
              </li>
              <% end %>
              <li>
                <%= link_to decline_request_path(request), method: :post do  %>
                <i id="decline" class="fas fa-ban">Decline</i>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/dashboard/_my_requests.html.erb
<div class="container">
  <div class="card-product">
    <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
    <div class="card-product-infos">
      <h2>Product name</h2>
      <p>Product description with <strong>relevant info</strong> only.</p>
    </div>
  </div>
</div>

app/views/dashboard/_outgoing_requests.html.erb
<div class="container">
  <div class="col mb-5">
    <div class="mb-50">

  <% my_requests.each do |request| %>
    <div class="card-product">
      <% if request.instrument.photo.attached? %>
         <%= cl_image_tag request.instrument.photo.key, class: 'card-product image', crop: :fill%>
      <% else %>
        <%= image_tag 'instrument-placeholder.jpg', class: 'card-product image' %>
      <% end %>
      <!-- <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" /> -->
        <div class="card-product-infos">
          <h2><%= request.instrument.name %></h2>
            <p>
              Date: <strong><%= request.start_date  %>
              till <%= request.end_date %></strong>
            </p>
            <p>Owners name: <%= request.instrument.user.first_name%></p>
            <% if request.status == "accepted" %>
            <p>Request accepted</p>
            <% elsif request.status == "declined" %>
            <p>Request declined</p>
            <% else %>
            <p>Pending</p>
            <% end %>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/dashboard/_request_list.html.erb
<div class="container">
  <div class="col mb-5">
    <div class="mb-50">

  <% @my_requests.each do |request| %>
    <div class="card-product">
      <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
        <div class="card-product-infos">
          <h2><%= request.instrument.name %></h2>
            <p>
              Date: <strong><%= request.start_date  %>
              till <%= request.end_date %></strong>
            </p>
            <p>Owners name: <%= request.instrument.user.first_name%></p>
            <% if request.status == "accepted" %>
            <p>Request accepted</p>
            <% elsif request.status == "declined" %>
            <p>Request eclined</p>
            <% else %>
            Pending
            <% end %>
        </div>
    </div>
    <% end %>
    </div>
  </div>
</div>

app/views/dashboard/profile.html.erb
<!-- <div class="container">
  <div class="row">
   <div class="col-xs-12 col-md-6 col-lg-3">
    <div>
    <%= current_user.first_name%>
    <%= current_user.email %>
    </div>
   </div>
  </div>
</div>

-->

<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">
<div class="container">
  <div class="row" style="border: solid; padding: 60px;">
    <div class="col-md-offset-2 col-md-8 col-lg-offset-3 col-lg-6">
     <div class="well profile" style="margin-bottom: -75px;">
      <div class="col-sm-12 d-flex">
        <div class="col-xs-12 col-sm-8">
          <h2><%= "#{current_user.first_name} #{current_user.last_name}" %></h2>
          <p><strong> <%= current_user.email %> </strong>  </p>
          <p style="width: 250px;"><strong>Instruments: </strong>
            <% current_user.instruments.pluck(:name).uniq.each do |name| %>
            <span class="tags"> <%= name %> </span>
            <% end %>
          </p>
        </div>
      </div>
      <div class="col-xs-12 divider text-center d-flex">
        <div class="col-xs-12 col-sm-4 emphasis">
          <h2><strong>+</strong></h2>
          <p><small>List instrument</small></p>
          <%= link_to "Create", new_instrument_path,
          class: "btn btn-primary"%>
       <!--  <button class="btn btn-primary btn-block"><span class="fa fa-plus-square"></span> Create </button>
       -->      </div>
       <div class="col-xs-12 col-sm-4 emphasis">
        <h2><strong><%= current_user.outgoing_requests.count %></strong></h2>
        <p><small>Requests</small></p>
        <%= link_to "Outgoing", profile_path(collapse: params[:collapse] == 'Outgoing' ? 'false' : 'Outgoing'),
        class: "btn btn-success"%>

        <!-- <button class="btn btn-success btn-block" ><span class="fa fa-user-square"></span> Outgoing </button> -->
      </div>
      <div class="col-xs-12 col-sm-4 emphasis">
        <h2><strong><%= current_user.requests.count %></strong></h2>
        <p><small>Requests</small></p>
        <%= link_to "Incoming", profile_path(collapse: params[:collapse] == 'Incoming' ? 'false' : 'Incoming'),
        class: "btn btn-info"%>
        <!-- <button class="btn btn-info btn-block"><span class="fa fa-user-square"></span> Incoming </button> -->
      </div>
    </div>
  </div>
</div>
</div>
<div style="margin-top: 50px;">
  <% if params[:collapse] == 'Outgoing' %>
    <%= render 'outgoing_requests', my_requests: @my_requests %>
  <% end %>
</div>
<div style="margin-top: 50px;">
  <% if params[:collapse] == 'Incoming' %>
  <%= render 'incoming_requests', requests: @requests %>
  <% end %>
</div>

app/views/instruments/edit.html.erb
<div class="container">
  <div class="row">
    <div class="form new col-8 offset-2 bg-white color-white">
      <%= simple_form_for @instrument do |f| %>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :price %>
      <%= f.submit "Update", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/instruments/index.html.erb
<!-- SEARCH FORM LANDING PAGE -->
<div class="banner">
  <div class="banner-container">
    <h1>InstruRent</h1>
    <h2><strong>Play your music.</strong> Anywhere. Anytime.</h2>
<!--     <div class="form-container bg-white color-white">
      <div class="main-form">
        <%#= simple_form_for :instrument, url: instruments_path, method: :get do |f| %>
        <%#= f.input :name, label: 'Find your instrument' %>
        <%#= f.submit "Search", class: "btn btn-primary" %>
        <%# end %>
      </div>
    </div>
 -->  </div>
</div>

<div class="container">
  <div class="message-container">
    <div class="messages">
      <h2>Do you have an instrument<br>you don't use anymore?</h2>
      <h3>Why not <strong>share</strong> with others and <strong>earn</strong> profit from your unused instrument?</h3>
      <%= link_to "Rent your instrument", new_instrument_path, class: "btn btn-secondary" %>
    </div>
    <%= image_tag "picture2.png", width: 500, height: 300, crop: :fill, class: 'messages-img' %>
  </div>

  <div class="message-container">
    <%= image_tag "picture1.png", width: 500, height: 300, crop: :fill, class: 'messages-img' %>

    <div class="messages">
      <h2>Do you want to try new instrument?</h2>
      <h3>but don't want to spend too much money?<br>Why not rent from others and try it out?</h3>

      <%= simple_form_for :instrument, url: instruments_path, method: :get do |f| %>
      <%= f.input :name, label: false, input_html: {size:"20",  autofocus: true, placeholder: "Search Instrument", class: "search-bar-down"} %>
      <% end %>
    </div>
  </div>
  <h2 id="headline">Instruments to borrow</h2>
</div>




<!-- CARDS LANDING PAGE -->
<div class="cards-container">
  <% @instruments.each do |instrument| %>
  <div class="instrument-card">
    <% if instrument.photo.attached? %>
    <%= cl_image_tag instrument.photo.key, class: 'instrument-img', height: 200, width: 350, crop: :fill %>
    <% else %>
    <%= image_tag 'instrument-placeholder.jpg', class: 'instrument-img' %>
    <% end %>

    <div class="card-details">
      <div class="card-instrument-infos">
        <%= link_to instrument.name, instrument_path(instrument), class: 'instrument-name' %>
        <h2 class="card-instument-pricing"><%= instrument.price %>€</h2>

      </div>

      <div class="card-instrument-details">
        <p><%= instrument.description %></p>
      </div>
    </div>
  </div>
  <% end %>
</div>

<footer class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at IntruRent!
  </div>
</footer>

app/views/instruments/new.html.erb
<div class="banner-owner">
  <div class="banner-owner-container">
    <h2 id="rent_instrument"><strong>Got an Instrument?</strong><br>Share with others.</h2>
    <div class="form-owner-container bg-white color-white">
      <div class="renting-form">
        <%= simple_form_for @instrument do |f| %>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :price %>
        <%= f.input :photo, as: :file %>
        <%= f.submit "Add Instrument", class: "btn btn-dark" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="container">
    <div class="message-container">
      <div class="messages">
        <h2>Easy to <strong>rent out</strong> your Instrument</h2>
        <h3>Sign up and start listing.</h3>
      </div>

      <%= image_tag "landing2-pic1.png", width: 500, height: 350, crop: :fill, class: 'messages-img' %>
    </div>

    <div class="message-container">
      <%= image_tag "landing2-pic2.png", width: 500, height: 350, crop: :fill, class: 'messages-img' %>

      <div class="messages">
        <h2 id="message-h2-tag">Share with the world</h2>
        <h3>Let other people enjoy your old bongo for example</h3>
      </div>
    </div>
</div>

<footer class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at IntruRent!
  </div>
</footer>

app/views/instruments/show.html.erb
<div class="container">

  <div class="instrument-details row">

    <div class="product-image col-4">
      <% if @instrument.photo.attached? %>
      <%= cl_image_tag @instrument.photo.key, height: 300, width: 350, crop: :fill %>
      <% else %>
      <%= image_tag 'instrument-placeholder.jpg', class: "default-img"%>
      <% end %>
    </div>

    <div class="product-info col-8">
      <div class="product-details">
        <h2><%= @instrument.name %></h2>
        <p><%= @instrument.description %></p>
        <h2 class="price"><%= @instrument.price %>€</h2>
      </div>

      <div class="book">
        <%= link_to "Book Now", new_instrument_request_path(@instrument), class: "btn btn-primary" %>
      </div>
    </div>

  </div>


  <div class="row">
    <div class="col-8 ">
      <div class="links">

        <div class="back">
          <%= link_to "<< Back", instruments_path %>
        </div>

        <div class="action">
          <% if current_user == @instrument.user %>
          <%= link_to edit_instrument_path(@instrument), method: :get do %>
          <i class="far fa-edit"></i>
          <% end %>
          <%= link_to instrument_path(@instrument), method: :delete do %>
          <i class="far fa-trash-alt"></i>
          <% end %>
          <% end %>
        </div>

      </div>
    </div>
  </div>

    <div class="row">
      <div class="col-8 offset-2">
        <div class="instrument-reviews">

          <div class="any-reviews">
            <% if @instrument.reviews.any? %>
            <% @instrument.reviews.each do |review| %>
            <p><%= review.instrument_review %></p>
              <% review.instrument_stars&.times do %>
              <i class="fas fa-star"></i>
              <% end %>
            <% end %>
          </div>

            <%else %>
              <div class="no-reviews">
              <p>There are no reviews for this instrument yet. <strong>Be the first!</strong></p>
            <%end %>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to image_tag("guitar.jpg"), instruments_path, class: 'navbar-brand'%>

  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>



  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="nav-item dropdown">
        <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/ssaunier" />
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Rent Out Your Instrument", new_instrument_path %>
          <%= link_to "Profile", profile_path ,class: 'dropdown-item'%>
          <%= link_to "My requests", profile_my_requests_path, class: 'dropdown-item' %>
          <%= link_to "Received requests",  profile_all_requests_path, class: 'dropdown-item' %>
          <%= link_to "Sign out", destroy_user_session_path, class: 'dropdown-item', method: :delete %>
        </div>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Log in", user_session_path %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path %>
      </li>
      <% end %>

<!--         <li class="nav-item active">
          <a class="nav-link" href="#">Messages</a>
        </li> -->
      </ul>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>TODO</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
</head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/alerts" %>
    <div class="main">
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>

</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/requests/new.html.erb
<div class="container col-4 offset-4">
  <%= simple_form_for [@instrument, @request] do |f| %>
  <%= f.input :start_date, as: :date, html5: true%>
  <%= f.input :end_date, as: :date, html5: true %>
  <%= f.submit "Book #{@instrument.name}", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/requests/show.html.erb
<div class="request-show">
  <div class="row">
   <div class="review new col-8 offset-2 bg-white color-white">

    <div class="thanks">
      <h1>Thank you for your Request!</h1>
      <p>Here are all the details of your booking:</p>
    </div>

    <div class="instrument-image" style="margin: auto;">
      <% if @instrument.photo.attached? %>
      <%= cl_image_tag @instrument.photo.key, class: "request-img", crop: :fill %>
     <% else %>
    <%= image_tag 'instrument-placeholder.jpg', class: "default-image", height: 300, width: 350 %>
      <% end %>
    </div>

    <div class="details">
      <h2>Name:</h2>
      <p><%= @instrument.name %></p>
      <h2>Description:</h2>
      <p><%= @instrument.description %></p>
    </div>

  </div>

  <div class="container">
    <div class="row">
      <div class="review new col-8 offset-2 bg-white color-white">
        <div class="ask-for-review">
          <p>We hope you're satisfied with your booking!<br><strong>Please share your opinion with us.</strong></p>
        </div>
        <%= simple_form_for [@request, @review] do |f| %>
        <%= f.input :instrument_review %>
        <%= f.input :instrument_stars %>
        <%= f.submit "Review", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>

app/views/reviews/create.html.erb
<div class="container">
  <div class="row">
    <div class="form new col-8 offset-2 bg-white color-white">
      <%= simple_form_for @review do |f| %>
      <%= f.input :user_review %>
      <%= f.input :user_stars %>
      <%= f.input :instrument_review %>
      <%= f.input :instrument_stars %>
      <%= f.submit "Review", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <div class="row">
    <div class="form new col-8 offset-2 bg-white color-white">
      <%= simple_form_for [@request, @review] do |f| %>
      <%= f.input :instrument_review %>
      <%= f.input :instrument_stars %>
      <%= f.submit "Review", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_footer.html.erb
<!-- <footer class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at IntruRent!
  </div>
</footer>
 -->

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="navbar-left-items">
    <%= link_to instruments_path do %>
      <%= image_tag "guitar.jpg", class: 'navbar-logo' %>
    <% end %>
    <%= simple_form_for :instrument, url: instruments_path, method: :get do |f| %>
      <%= f.input :name, label: false, input_html: {size:"20", maxlength:"30", autofocus: true, placeholder: "Search", class: "search-bar"} %>
    <% end %>
  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="nav-item dropdown">
        <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/ssaunier" />
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Rent Your Instrument", new_instrument_path, class: 'dropdown-item' %>
          <%= link_to "Dashboard", profile_path ,class: 'dropdown-item'%>
          <%= link_to "Sign out", destroy_user_session_path, class: 'dropdown-item', method: :delete %>
        </div>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Log in", user_session_path, class: 'nav-bar-button' %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class: 'nav-bar-button' %>
      </li>
      <% end %>
    </ul>
  </div>
</div>